### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by loriab** [Masterluke87/psixas#3]
Hi, If you're interested, we can mention this plugin in a table in the upcoming Psi4 paper. Needed:

* author name (rather than GitHub id)
* maintaining research group or entity
* literature reference for software or theory, if any

Thanks!

**Comment by Masterluke87** [comment]
Hi Lori,

Thanks a lot! 

- Main author is me, Christopher Ehlert (christopher.ehlert@h-its.org)
- I'm located at:
Heidelberg Institute for Theoretical Studies 
Schloss-Wolfsbrunnenweg 35
69118 Heidelberg
Germany
- A paper about the plugin is in preparation... (I will let you know, once it's accepted)

Thanks again,
Christopher

**Comment by loriab** [comment]
Hi Christopher,

Thank you -- table line completed! Yes, please do post your paper when it's available.

Sincerely,
Lori
