### ISSUE TITLE
About Installation

### ISSUE THREAD

**Issue by ghost** [Masterluke87/psixas#4]
I have a question about installation.
I don't have a directly /path/to/psi4Plugins/.
First step, Should I make a /path/to/psi4Plugins/? (I already installed psi4)

**Comment by Masterluke87** [comment]
Hi black-suit,

the directory "/path/to/psi4Plugins/" is just a placeholder for the location where you would like to install psixas (usually where also other PSI4 plugins are installed). 

If you don't have any other plugins installed, just create a folder wherever you think it's suitable.
