### ISSUE TITLE
could not broadcast input array from shape (247,) into shape (0,) !

### ISSUE THREAD

**Issue by MaxParadiz** [Masterluke87/psixas#6]
I have installed a recent version of psi4 (1.5a1.dev151), using python 3.9, and I get the following error for the 3,3,3-Trifluoropropanol example (and a similar one for the H2O example):

```
Traceback (most recent call last):
  File "/home/max/.local/inst/psi4/bin/psi4", line 333, in <module>
    exec(content)
  File "<string>", line 42, in <module>
  File "/home/max/.local/inst/psi4/lib/psi4/driver/driver.py", line 599, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/max/.local/plug/psi4/psixas/pymodule.py", line 71, in run_psixas
    DFTGroundState(mol,func,PREFIX=psi4.core.get_local_option("PSIXAS","PREFIX"))
  File "/home/max/.local/plug/psi4/psixas/ksgs.py", line 335, in DFTGroundState
    uhf.occupation_a().np[:] = occa

ValueError: could not broadcast input array from shape (247,) into shape (0,)

Printing out the relevant lines from the Psithon --> Python processed input file:
    core.set_global_option("BASIS", "def2-TZVP")
    core.set_local_option("PSIXAS", "PREFIX", "TRIFLUOR")
    core.set_local_option("PSIXAS", "MODE", "GS")
    core.set_local_option("SCF", "REFERENCE", "uks")
    core.set_local_option("SCF", "SCF_TYPE", "MEM_DF")
--> energy('psixas',functional='B3LYP')


!--------------------------------------------------------------------!
!                                                                    !
!  could not broadcast input array from shape (247,) into shape (0,) !
!                                                                    !
!--------------------------------------------------------------------!
```

Could this be an issue with my compilation, or is the plugin incompatible with the more recent versions of psi4?

Thanks!
Max

**Comment by MaxParadiz** [comment]
Commenting out the following in pymodule.py, ksgs.py, and ksex.py will fix the issue:

```
uhf.occupation_a().np[:] = occa
uhf.occupation_b().np[:] = occb
```

Since uhf.occupation_a() and uhf_occupation_b() are not used downstream, leaving them as empty arrays causes no problems. I did not find a way to set these Vectors properly.

**Comment by Masterluke87** [comment]
Hi Max,

many thanks for this report. This seems to be an issue with the current development version. I tried Psi4 1.4.1 and it worked without any problems. Indeed, those lines seem rather useless ^^, but I think they were required to get correct Molden files. Anyhow the whole Psi4 Molden interface seems to be under development. 

When I tried version 1.5x (from the conda repo), it failed as you described, and also the Molden files are broken when the lines are removed. However, as things may change in the Psi4 development, I would like to wait for the next stable release before making adjustments.

So in case you need the Molden files, is the stable release (1.4.1) an option for you?

Thanks again,
Christopher

**Comment by MaxParadiz** [comment]
Aha, that makes sense! I did not notice the effect of removing them because I do not use the Molden files. 

The program works great for me without these lines. The spectra match the absolute experimental energies quite closely, so I am very happy with that! Thanks a lot.

Max

**Comment by Masterluke87** [comment]
Nice to hear that! Let me know if you encounter any other issues.

Best,
Christopher
