### ISSUE TITLE
how to view the water_b.spectrum ?

### ISSUE THREAD

**Issue by SongQi-at-NWU** [Masterluke87/psixas#7]
Dear Masterluke,
    I want to know how to open the water_b.spectrum file. 
 thank you

**Comment by Masterluke87** [comment]
Hi SongQi,

have a look in the plot.py script in the "Examples/00_TP_H2O/" folder. That should give you a hint!

**Comment by SongQi-at-NWU** [comment]
yes i got it. ^_^


发件人：Masterluke ***@***.***>
发送日期：2023-11-18 20:42:53
收件人：Masterluke87/psixas ***@***.***>
抄送人：
主题：Re: [Masterluke87/psixas] how to view the water_b.spectrum ? (Issue #7)

Hi SongQi,

have a look in the plot.py script in the "Examples/00_TP_H2O/" folder. That should give you a hint!

**Comment by SongQi-at-NWU** [comment]
Compile psixas with psi4:
1.  it is necessary to install pybind11:            pip install pybind11
2.  install eigen3:                                            sudo apt-get install libeigen3-dev
3.  install boost:                                             sudo apt-get install libboost-all-dev
first.
5. Then, modify the ~/Psi4/share/cmake/psi4/psi4PluginCache.cmake
“
set(CMAKE_C_COMPILER          "/usr/bin/gcc" CACHE STRING "")
set(CMAKE_CXX_COMPILER        "/usr/bin/g++" CACHE STRING "")
set(CMAKE_Fortran_COMPILER    "/usr/bin/gfortran" CACHE STRING "")

”
Finally,

 $(psi4 --plugin-compile)
and
make
________________________________
From: 宋齐 ***@***.***>
Sent: Saturday, November 18, 2023 4:44 AM
To: Masterluke87/psixas ***@***.***>
Subject: Re: Re: [Masterluke87/psixas] how to view the water_b.spectrum ? (Issue #7)

yes i got it. ^_^

________________________________
发件人：Masterluke ***@***.***>
发送日期：2023-11-18 20:42:53
收件人：Masterluke87/psixas ***@***.***>
抄送人：
主题：Re: [Masterluke87/psixas] how to view the water_b.spectrum ? (Issue #7)

Hi SongQi,

have a look in the plot.py script in the "Examples/00_TP_H2O/" folder. That should give you a hint!

―

**Comment by Masterluke87** [comment]
Hey SongQi,

it might be easier if you use a conda environment. Have a look here: https://psixas.readthedocs.io/en/latest/install.html
